sudo: false
language: go
go:
  - 1.9

script:
  - make get-build-deps build

after_success:
 - curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/avarabyeu/yeelight"
 - bash <(curl -s https://codecov.io/bash)
